### ISSUE TITLE
undefined method `+' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by hayate** [kmewhort/git.legal-codeclimate#3]
```code
/usr/src/app/app/services/service/yarn_lockfile/parse.rb:28:in `find_line_number': undefined method `+' for nil:NilClass (NoMethodError)
	from /usr/src/app/app/services/service/yarn_lockfile/parse.rb:11:in `block in call'
	from /usr/src/app/app/services/service/yarn_lockfile/parse.rb:5:in `each'
	from /usr/src/app/app/services/service/yarn_lockfile/parse.rb:5:in `map'
	from /usr/src/app/app/services/service/yarn_lockfile/parse.rb:5:in `call'
	from /usr/src/app/lib/micro_service.rb:10:in `call'
	from /usr/src/app/app/services/service/yarn_lockfile/scan.rb:9:in `library_identifiers'
	from /usr/src/app/app/services/service/scan_manifest_base.rb:7:in `call'
	from /usr/src/app/app/services/service/yarn_lockfile/scan.rb:4:in `call'
	from /usr/src/app/lib/micro_service.rb:10:in `call'
	from /usr/src/app/app/services/service/scan_project.rb:21:in `call'
	from /usr/src/app/lib/micro_service.rb:10:in `call'
	from /usr/src/app/bin/git-legal-cc-scan:6:in `<main>'
```

**Comment by hayate** [comment]
Just wanted to add a bit more info, the error appears on codeclimate on a php repository. Below is a screenshot of the error.

![git-legal](https://user-images.githubusercontent.com/92108/46510926-9b364c80-c886-11e8-97a3-6a605dbc84b6.png)
